name: WildDuel
version: 1.0
main: com.wildduel.WildDuel
api-version: 1.21
commands:
  wd:
    description: Wild Duel command.
    usage: /wd <set|sp|start|ts>
  tpa:
    description: Request to teleport to a team member.
    usage: /tpa <player>
  tpacancel:
    description: Cancel a TPA request.
    usage: /tpacancel
  tparesponse:
    description: Accept or deny a TPA request.
    usage: /tparesponse <accept|deny> <player>
  팀선택:
    description: Open the team selection GUI.
    usage: /팀선택
